project:
  type: website
  output-dir: docs

website:
  title: "350quiz02_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lifeexp-gdp.qmd
        text: Life Expectancy vs GDP
      - href: lifeexp-pop.qmd
        text: Life Expectancy vs Population
      - href: country-trends.qmd
        text: Country Trends

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



